### ISSUE TITLE
Puppeteer crash due to dev profile error

### ISSUE THREAD

**Issue by ringge** [Songkeys/Translateer#19]
I'm running Translateer using Option 2, Serve locally.
After a while, the app crashed and showed below error

`/root/apps/translateer/node_modules/@puppeteer/browsers/lib/cjs/launch.js:271
                reject(new Error([
                       ^

Error: Failed to launch the browser process! undefined
[1301414:1301414:1205/220205.443107:ERROR:process_singleton_posix.cc(335)] Failed to create /tmp/puppeteer_dev_profile-IEw0m8/SingletonLock: No such file or directory (2)
[1301414:1301414:1205/220205.443424:ERROR:chrome_main_delegate.cc(553)] Failed to create a ProcessSingleton for your profile directory. This means that running multiple instances would start multiple browser processes rather than opening a new window in the existing process. Aborting now to avoid profile corruption.`

**Comment by songkeys** [comment]
I'm not sure about this. But I guess it's something to do with `userDataDir` so I pushed a [fix](https://github.com/Songkeys/Translateer/commit/7662b987a2a58d64e8a2bdf4533425a860165213) just now. Could you try again to see if the error is still there?

**Comment by ringge** [comment]
thanks so much for the prompt reply, let me try the new fix

**Comment by ringge** [comment]
Hey, after a few times of browser reinit, puppeteer still crash

`/root/apps/translateer/node_modules/@puppeteer/browsers/lib/cjs/launch.js:271
                reject(new Error([
                       ^

Error: Failed to launch the browser process! undefined
[1309925:1309925:1206/101231.338579:ERROR:process_singleton_posix.cc(335)] Failed to create /root/apps/translateer/tmp/translateer-data/SingletonLock: File exists (17)
[1309925:1309925:1206/101231.339856:ERROR:chrome_main_delegate.cc(553)] Failed to create a ProcessSingleton for your profile directory. This means that running multiple instances would start multiple browser processes rather than opening a new window in the existing process. Aborting now to avoid profile corruption.
[1206/101231.351579:ERROR:nacl_helper_linux.cc(354)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly`

**Comment by songkeys** [comment]
May I ask:

-  What platform are you running on?
-  "After a few attempts of browser reinit" - could you please describe more clearly? Did you restart the process multiple times?
-  "After some time, the app crashed and displayed the following error" - Did this error occur when you started it or after running it for a while?

**Comment by songkeys** [comment]
Here is another issue related: https://github.com/puppeteer/puppeteer/issues/10517

I guess it's a problem with the new introduced `headless: true` option from pupetter. As an attempt, you could try change this line:

https://github.com/Songkeys/Translateer/blob/7662b987a2a58d64e8a2bdf4533425a860165213/src/browser/pagepool.ts#L48

to:

```ts
headless: true,
```

and rebuild with `npm run build` then restart to see if it works.

**Comment by ringge** [comment]
> May I ask:
> 
>     * What platform are you running on?
> 
>     * "After a few attempts of browser reinit" - could you please describe more clearly? Did you restart the process multiple times?
> 
>     * "After some time, the app crashed and displayed the following error" - Did this error occur when you started it or after running it for a while?

1. I'm running on Ubuntu LTS 22.04.3
2. To clarify, this refer to the _resetInterval function in papepool.ts, where I saw it called initBrowser and initPages every 1 hour. So when I first run the app, everything runs ok, but after a few hours, where the initBrowser and initPages have run a few times, the error occurred
3. As explained in 2

**Comment by ringge** [comment]
> Here is another issue related: [puppeteer/puppeteer#10517](https://github.com/puppeteer/puppeteer/issues/10517)
> 
> I guess it's a problem with the new introduced `headless: true` option from pupetter. As an attempt, you could try change this line:
> 
> https://github.com/Songkeys/Translateer/blob/7662b987a2a58d64e8a2bdf4533425a860165213/src/browser/pagepool.ts#L48
> 
> to:
> 
> ```ts
> headless: true,
> ```
> 
> and rebuild with `npm run build` then restart to see if it works.

let me try this now, thanks

**Comment by songkeys** [comment]
> To clarify, this refer to the _resetInterval function in papepool.ts, where I saw it called initBrowser and initPages every 1 hour. So when I first run the app, everything runs ok, but after a few hours, where the initBrowser and initPages have run a few times, the error occurred

This function did have a flaw. I just pushed a [commit](https://github.com/Songkeys/Translateer/commit/21e6cd64fcdfdc10a5bf56d01b6d3b0062acb347#). Could you try again?

Specifically, it might due to the reiniting happens before the old browsers compleletly closing.

**Comment by ringge** [comment]
> > To clarify, this refer to the _resetInterval function in papepool.ts, where I saw it called initBrowser and initPages every 1 hour. So when I first run the app, everything runs ok, but after a few hours, where the initBrowser and initPages have run a few times, the error occurred
> 
> This function did have a flaw. I just pushed a [commit](https://github.com/Songkeys/Translateer/commit/21e6cd64fcdfdc10a5bf56d01b6d3b0062acb347#). Could you try again?
> 
> Specifically, it might due to the reiniting happens before the old browsers compleletly closing.

Great, trying now, will update how it goes

**Comment by songkeys** [comment]
You could shorten the reiniting time to test :)

**Comment by ringge** [comment]
> You could shorten the reiniting time to test :)

Oh yes, silly me :)

**Comment by ringge** [comment]
I reduced the reiniting time and tested so it looks good now
Only thing is when I run api request during the browser reinitiation, sometimes I get 500 response like this, it doesn't crash the app, so it should be fine, but anyway just wanted to report back.
Thanks so much

"res":{"statusCode":500},"err":{"type":"TargetCloseError","message":"Target closed","stack":"TargetCloseError: Target closed\n    at /root/apps/translateer/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:192:51\n    at /root/apps/translateer/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:1:732\n    at Array.map (<anonymous>)\n    at Object.emit (/root/apps/translateer/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:1:716)\n    at CdpCDPSession.emit (/root/apps/translateer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:91:23)\n    at CdpCDPSession._onClosed (/root/apps/translateer/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:115:14)\n    at Connection.onMessage (/root/apps/translateer/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:132:25)\n    at WebSocket.<anonymous> (/root/apps/translateer/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:52:32)\n    at callListener (/root/apps/translateer/node_modules/ws/lib/event-target.js:290:14)\n    at WebSocket.onMessage (/root/apps/translateer/node_modules/ws/lib/event-target.js:209:9)","name":"TargetCloseError"},"msg":"Target closed"}

**Comment by songkeys** [comment]
Glad to know it solves the issue.

> Only thing is when I run api request during the browser reinitiation, sometimes I get 500 response like this

Because in that period, the browser is restarting so can't reach to the web page. We have to do the restarting approach because of [a memory leak issue reported](https://github.com/Songkeys/Translateer/issues/7) a while ago.

I'll see if I could improve it a little bit later.

**Comment by therealsamsquanch** [comment]
My proposal:

1. add a global variable "_busy"
2. before actually restarting, set _busy to TRUE and wait 10 seconds to let current translations to finish
3. when the API receives new translation requests, before proceeding, it checks if _busy === TRUE. If it is, return an HTTP 503
