### ISSUE TITLE
Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.

### ISSUE THREAD

**Issue by nanoia** [Songkeys/Translateer#6]
Request: Get `/api?text=hello&from=auto&to=zh-CN`
Response:
```
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed."
}
```
the log from docker:
```
{"level":50,"time":1665212967455,"pid":75,"hostname":"61b9ed4c4d57","reqId":"req-e","req":{"method":"GET","url":"/api?text=hello&from=auto&to=zh-CN","hostname":"192.168.10.21:8999","remoteAddress":"192.168.10.81","remotePort":8813},"res":{"statusCode":500},"err":{"type":"Error","message":"Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.","stack":"Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.\n    at CDPSession.send (/usr/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:285:35)\n    at next (/usr/app/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:34:41)\n    at CDPSession.send (/usr/app/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:75:16)\n    at ExecutionContext._ExecutionContext_evaluate (/usr/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:210:46)\n    at ExecutionContext.evaluateHandle (/usr/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:158:107)\n    at IsolatedWorld.document (/usr/app/node_modules/puppeteer/lib/cjs/puppeteer/common/IsolatedWorld.js:189:77)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async IsolatedWorld.$eval (/usr/app/node_modules/puppeteer/lib/cjs/puppeteer/common/IsolatedWorld.js:199:26)"},"msg":"Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed."}
```

**Comment by songkeys** [comment]
Do you have logs while the app gets starting?

**Comment by nanoia** [comment]
```

> translateer@2.0.0 bootstrap
> npm ci && npm run build && npm run prod


added 178 packages, and audited 179 packages in 1m

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 8.15.0 -> 8.19.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.19.2>
npm notice Run `npm install -g npm@8.19.2` to update!
npm notice 

> translateer@2.0.0 build
> rm -rf dist && tsc && cp -R src/public dist/public


> translateer@2.0.0 prod
> node dist/app.js

connecting to puppeteer...

d
initializing pages...
no privacy consent
no privacy consent
no privacy consent
no privacy consent
no privacy consent
ready
{"level":30,"time":1665296070451,"pid":76,"hostname":"e1381e5d462c","msg":"Server listening at http://0.0.0.0:8999"}
{"level":30,"time":1665296767128,"pid":76,"hostname":"e1381e5d462c","reqId":"req-1","req":{"method":"GET","url":"/api?text=hello&from=auto&to=zh-CN","hostname":"192.168.50.43:8999","remoteAddress":"192.168.50.22","remotePort":1032},"msg":"incoming request"}
{"level":50,"time":1665296767135,"pid":76,"hostname":"e1381e5d462c","reqId":"req-1","req":{"method":"GET","url":"/api?text=hello&from=auto&to=zh-CN","hostname":"192.168.50.43:8999","remoteAddress":"192.168.50.22","remotePort":1032},"res":{"statusCode":500},"err":{"type":"Error","message":"Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.","stack":"Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.\n    at CDPSession.send (/usr/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:285:35)\n    at next (/usr/app/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:34:41)\n    at CDPSession.send (/usr/app/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:75:16)\n    at ExecutionContext._ExecutionContext_evaluate (/usr/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:210:46)\n    at ExecutionContext.evaluateHandle (/usr/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:158:107)\n    at IsolatedWorld.document (/usr/app/node_modules/puppeteer/lib/cjs/puppeteer/common/IsolatedWorld.js:189:77)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async IsolatedWorld.$eval (/usr/app/node_modules/puppeteer/lib/cjs/puppeteer/common/IsolatedWorld.js:199:26)"},"msg":"Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed."}
{"level":30,"time":1665296767151,"pid":76,"hostname":"e1381e5d462c","reqId":"req-1","res":{"statusCode":500},"responseTime":21.867684960365295,"msg":"request completed"}
```

**Comment by songkeys** [comment]
This is a tricky one. I can't reproduce this on my machine.

I can only assume that you were running this in mainland China that blocks Google Translate? If so, you may need a proxy for the docker. If not, could you try `npm run debug` to open up the visible browser and see what's going on?

**Comment by nanoia** [comment]
> This is a tricky one. I can't reproduce this on my machine.
> 
> I can only assume that you were running this in mainland China that blocks Google Translate? If so, you may need a proxy for the docker. If not, could you try `npm run debug` to open up the visible browser and see what's going on?

Sorry for the late reply, now I can't reproduce the problem either, maybe my proxy node was broken at that time, please close this issue, thanks for your reply.
